apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: APP_NAME-ingress
  namespace: APP_NAME-system
spec:
  rules:
  - host: APP_NAME.teoo.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: APP_NAME-svc
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - APP_NAME.teoo.io
    secretName: APP_NAME-ingress-cert
